version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: ./main.go
    binary: plugkit
    dir: .
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w
    flags:
      - -trimpath
    hooks:
      post: |
        if [ "{{ .Os }}" = "darwin" ]; then
          # Remove quarantine attribute if it exists
          if [ -f "{{ .Path }}" ]; then
            codesign --force --options runtime --sign - "{{ .Path }}" || true
          fi
        fi

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
    allow_different_binary_count: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch 