version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: arm64
    main: ./main.go
    binary: plugkit
    dir: .
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/*
      - completions/*
      - man/*
    allow_different_binary_count: true

signs:
  - cmd: gpg
    signature: "${artifact}.sig"
    artifacts: all
    args: ["--batch", "--yes", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
    stdin: '{{ .Env.GPG_PRIVATE_KEY }}'
    stdin_file: '{{ .Env.GPG_PRIVATE_KEY_FILE }}'

macos:
  - name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/*
      - completions/*
      - man/*
    allow_different_binary_count: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch 