version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    main: ./main.go

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}_
      v{{ .Version }}
    format: zip
    files:
      - LICENSE
      - README.md