name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Linux binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/myapp-linux-amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-linux-amd64
          path: dist/myapp-linux-amd64
