name: build-and-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Get version
        id: get_version
        run: |
          # Get the latest version from git tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          # Increment the patch version
          NEW_VERSION=$(echo $LATEST_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git tag ${{ steps.get_version.outputs.version }}
          git push origin ${{ steps.get_version.outputs.version }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 'v2.9.0'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

      - name: Compress distribution folders
        run: |
          cd dist
          zip -r plugkit_darwin_amd64_v1.zip plugkit_darwin_amd64_v1/
          zip -r plugkit_linux_amd64_v1.zip plugkit_linux_amd64_v1/
          zip -r plugkit_windows_amd64_v1.zip plugkit_windows_amd64_v1/

      - name: Handle latest release
        run: |
          # Delete existing latest release if it exists
          if gh release view latest &>/dev/null; then
            gh release delete latest --yes
          fi
          
          # Create new latest release
          gh release create latest \
            --title "Latest Release" \
            --notes "Latest release of plugkit" \
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 