name: build-and-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 'v2.9.0'
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

      - name: Compress distribution folders
        run: |
          cd dist
          zip -r plugkit_darwin_amd64_v1.zip plugkit_darwin_amd64_v1/
          zip -r plugkit_linux_amd64_v1.zip plugkit_linux_amd64_v1/
          zip -r plugkit_windows_amd64_v1.zip plugkit_windows_amd64_v1/

      - name: Get latest release
        id: get_latest_release
        uses: bruceadams/get-release@v3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to latest release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/plugkit_darwin_amd64_v1.zip
            dist/plugkit_linux_amd64_v1.zip
            dist/plugkit_windows_amd64_v1.zip
          tag_name: latest
          name: Latest Release
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 