name: build-and-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 'v2.9.0'
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

      - name: Compress distribution folders
        run: |
          cd dist
          zip -r plugkit_darwin_amd64_v1.zip plugkit_darwin_amd64_v1/
          zip -r plugkit_linux_amd64_v1.zip plugkit_linux_amd64_v1/
          zip -r plugkit_windows_amd64_v1.zip plugkit_windows_amd64_v1/

      - name: Create or update latest release
        run: |
          # Check if latest release exists
          if gh release view latest &>/dev/null; then
            # Update existing release
            gh release upload latest dist/*.zip --clobber
          else
            # Create new release
            gh release create latest \
              --title "Latest Release" \
              --notes "Latest release of plugkit" \
              dist/*.zip
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 